= Visur

VI Surpassed => Visur

a powerful vim-like editor which extends vim to handle concepts that could only previously be handled well by a full integrated dev environment tool.

image:https://img.shields.io/badge/vert.x-4.1.3-purple.svg[link="https://vertx.io"]

This application was generated using http://start.vertx.io

##Main Visur Features:
1. Edit objects not just text files. Type-sensitive editor. Because of that, it is also language-independent
2. Client-server architetures. Multiple users can edit the same files at the same time. Like Google Docs
3. Conditional logic & arithmetic operation within macro definition
4. Interface independent. Can be used in the browser, command line, or within a graphical window
5. Can edit streams of data instead of just static files. For example, a network flow. Can work like a network analysis tool, capturing data in the moment

== Building

To launch your tests:
```
./gradlew clean test
```

To package your application:
```
./gradlew clean assemble
```

To run your application:
```
./gradlew clean run
```

== Help

* https://vertx.io/docs/[Vert.x Documentation]
* https://stackoverflow.com/questions/tagged/vert.x?sort=newest&pageSize=15[Vert.x Stack Overflow]
* https://groups.google.com/forum/?fromgroups#!forum/vertx[Vert.x User Group]
* https://gitter.im/eclipse-vertx/vertx-users[Vert.x Gitter]


