package com.ple.visur;

public enum EditorModelKey {
  canvasWidth,
  canvasHeight,
  commandCursor,
  commandStateContent,
  contentY,
  editorContent,
  editorMode,
  globalVariableMap,
  isInCommandState,
  keyBuffer,
  keyPressed,
  keymapMap,
  modeToKeymap,
  operator,
  operatorToService,
  virtualX,
  virtualXIsAtEndOfLine,
  quantum,
  executionData,
  quantumNameToQuantum,
  quantumStart,
  quantumEnd,
  newlineIndices,
  cursorPositionDCHolder,
  editorSubmodeStack,
  keyToQuantumName,
  span,
  isAtQuantumStart,
  previousSearchTarget,
  previousSearchDirectionWasForward,
  lineWrapping,
}
