package com.ple.visur;

public enum EditorModelKey {
  canvasHeight,
  canvasWidth,
  commandCursor,
  commandStateContent,
  contentX,
  contentY,
  editorContent,
  editorMode,
  globalVariableMap,
  isInCommandState,
  keyBuffer,
  keyPressed,
  modeToHandlerArray,
  modeToKeymap,
  operator,
  operatorToService,
  virtualX,
  virtualXIsAtEndOfLine,
  quantum,
  executionData,
  quantumMap,
  quantumStart,
  quantumEnd,
}
