package com.ple.visur;

public enum Operator {
  absoluteMove,
  add,
  cursorLeft,
  cursorRight,
  cursorDown,
  cursorUp,
  moveCursorToBeginningOfNextWord,
  moveCursorToBeginningOfCurrentLine,
  moveCursorToEndOfCurrentLine,
  moveCursorToFirstNonSpaceInCurrentLine,
  enterInsertMode,
  enterEditingMode,
  insertNewLine,
  insertChar,
  deleteCurrentChar,
  moveRight,
  literalNumberOperator,
  literalStringOperator,
  assignmentOperator,
  nativeOperator,
  recallOperator,
}
